# Permalinks
permalink:        pretty

# Setup
url:              http://captaink.org

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            åº·å­é¾™çš„åšå®¢

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  

# The tags listed as entries in the sidebar
sidebar_tags:     [notes, blablabla]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/side.jpg
color:            '#A85641'

author:
  name:           'åº·å­é¾™'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        kangzlong
  github:         MrKang

  # Setting a disqus username will enable the comment section
  disqus:         captaink

  # This photo will be used in the about section
  photo:          /public/img/photo.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    å˜¿ï¼Œæˆ‘æ˜¯ä¸€ä¸ªåˆšä».NETè½¬åˆ°iOSçš„ç¨‹åºçŒ¿ï¼Œswiftè„‘æ®‹ç²‰ğŸ˜‚.
    
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
